import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
import Header from './header'
import Navigation from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Halalvar',
  description: 'Generated by create next app',
}

interface Props {
  title: string | undefined | null;
  // backLink?: string;
  // halalStatus: "halal" | "mushbooh" | "haram"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
  title: Props,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer>
          <Navigation></Navigation>
        </footer>
      </body>
    </html>
  )
}