import { FC, ReactNode } from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Halalvar',
    description: 'Generated by create next app',
  }

interface layoutProps {
  children: ReactNode
}

const layout: FC<layoutProps> = ({ children }) => {
  return <div className='bg-red-200'>{children}</div>
}

export default layout