name: Cypress Tests

on: [push]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Run Cypress Tests
      run: npx run cypress

    - name: Upload Cypress Test Results
      run: |
        npx cypress run --record --key <YOUR_RECORD_KEY> --group <YOUR_GROUP_NAME>
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        CYPRESS_PROJECT_ID: <YOUR_PROJECT_ID>
